README.md

Make it clear for users reading the README as a quickstart guide where they can get everything they need.

Update README to specify where the truck_v7.riv is

---

.github/workflows/publish-release.yml
example/ios/Podfile.lock
package.json
rive-react-native.podspec

Update rive-ios version to sort out bitcode
Flip rive-react-native to build on merge to main! 
NOTE: merging will trigger a build

Fix bitcode

---

android/src/main/java/com/rivereactnative/RiveReactNativeView.kt

Getting the following errors when trying to build an android app:
```
e: .../node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt: (48, 24): Type mismatch: inferred type is ExceptionsManagerModule? but ExceptionsManagerModule was expected
e: .../node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt: (48, 50): Type mismatch: inferred type is ExceptionsManagerModule? but ExceptionsManagerModule was expected
```
Changing `ExceptionsManagerModule` to nullable to get this working

fix: make ExceptionsManagerModule nullable

---

android/build.gradle

Updates rive-android to be the latest version, no fixes here just updating java/kotlin/gradle in android.

chore: bump rive-android release

---

src/Rive.tsx
src/types.ts

Addresses #140  - for some reason, scrolling the Rive view is calling `onPressOut` with undefined coordinates, and thus causing issues at the iOS and most likely Android level too when we call into the native Listeners logic. Docs on React Native are a bit unclear as to the behavior around `onPressOut` and scrolling, so not quite sure why this is, but this should help fix things for now, safely.

fix: prevent calling listener logic with potentially undefined coordinate values

---

android/build.gradle
example/android/build.gradle
example/android/gradle.properties

On February 3 2021, JFrog [announced that they will be shutting down Bintray and JCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
So remove jcenter() and replace it with mavenCentral().
Upgrade also some necessary tools for react native like Flipper to version 0.99.

fix(android): remove jcenter repository

---

.github/workflows/publish-release.yml

No longer needed in the manual dispatch workflow for publishing the NPM package

fix: remove if statement in publish workflow

---

android/build.gradle
android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt
example/android/app/src/main/java/com/example/rivereactnative/MainActivity.java
example/ios/Podfile.lock
example/package.json
example/src/Simple.tsx
example/yarn.lock
package.json

Previously with 4.0.0 release of React Native, we had an issue of simply displaying Rive on Android. With some recent changes in the underlying Android runtime, as well as reverting back to using `onAfterUpdateTransaction` in the RiveReactNativeViewManager rather than coordinating attach/detach lifecycles in the binding RiveReactNativeView layer, this should address simply displaying Rive for Android.

Fix: update Android dependency to fix lifecycle issues

---

example/ios/Podfile.lock
example/package.json
example/yarn.lock
rive-react-native.podspec

As part of this we have fixed a couple of memory leaks on rive ios.
Specifically one involving circular references in how our http delegates worked, this would keep old views alive. 
We have also updated how we use Skia graphics contexts. We use Skia as our renderer & it has a a graphics context that can cache some rendered outputs. Previously we would simply let this be managed entirely by Skia with a single permanent shared context, but we now clear the context when no more RiveViews are in memory.
There is still some overhead to using Skia that we cannot mitigate, and so you will see an additional memory footprint after closing a riveView. This footprint will be more limited, and & will not grow significantly with every additional RiveFile. different animations may require Skia to …

Bump ios dependency

---

android/build.gradle
example/ios/Podfile.lock
package.json
rive-react-native.podspec

- fix leak in move operator= on SimpleArray (CPP runtime)

chore: bump to v6.0.2

---

android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt
package.json

Fixes: https://github.com/rive-app/rive-react-native/issues/198
This may need to be revisited on native Android, as there could be some discussion on making the current controller refcount more decoupled to how it is currently handled. But I could not replicate the issue natively, and it could be that ReactNative is managing the view is unique and not something that would cause issues in native use.
It may also be that we change the view creation logic in ReactNative in the future, so I'm opting in for a patch that ensures RN behaves sensibly with regards to the controller ref count on view navigation. Also adding a lot of code comments + considerations/alternatives.

fix: controller refcount out of sync with view

---

android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
package.json

Fixes https://github.com/rive-app/rive-react-native/issues/212
TODO:
This is hotfix. A solution needs to be investigated to keep ReactNative and Android in sync for future changes.

fix: lifecycle and refcount issue when navigating pages

---

ios/RiveReactNative-Bridging-Header.h
ios/RiveReactNativeView.swift

RE: https://github.com/rive-app/rive-react-native/issues/214
When upgrading to React Native 0.73, it seems views receive experimental and unused props from React Native. By deriving the custom view `RiveReactNativeView` from `RCTView` from React Native instead of `UIView`, stubs for these props are provided for free. 
I have checked this makes the specific issue I'm trying to fix go away and seems to run just fine, but please help me to understand if there may be unintended consequences or a better approach that might be more suitable.
Thanks in advance!

fix: "Exception thrown while executing UI block: -[rive_react_native.RiveReactNativeView setOnClick:]: unrecognized selector sent to instance"

---

ios/RiveReactNativeView.swift

I was able to consistently crash my React Native app when Hot Module Reloading was triggered. Removing the implicit optional unwrapping and making that explicit within RiveReactNativeView fixed the crashes I was running into.

fix nil safety in RiveReactNativeView.swift

---

android/build.gradle
android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt
example/android/build.gradle
ios/utility.swift
package.json
rive-react-native.podspec

Bumping iOS to 5.10.0 and Android 9.3.0
Notes:
- Needed to bump the minSDKVersion to 24 to resolve dexing errors when building. Its possible there were other dependency conflicts which weren't obvious, so perhaps this change isn't necessary.

chore: bump iOS and Android dependencies to get latest bug fixes

---

package.json

Major version bump for pulling in iOS 5.10.0 and Android 9.3.0

chore: bump major version for iOS and Android updates

---

android/build.gradle
package.json

Bump Rive Android, with a fix for: https://github.com/rive-app/rive-android/issues/324

chore: release v7.0.1

---

android/build.gradle

follow https://stackoverflow.com/questions/76108428/how-do-i-fix-namespace-not-specified-error-in-android-studio
and https://github.com/getsentry/sentry-react-native/blob/main/android/build.gradle#L17C5-L20C6
which fixed Android Gradle Plugin error >= 8.x.x

add Android RN 0.73 Support 

---

example/ios/Podfile.lock
package.json
rive-react-native.podspec

- Includes a new API to set the default renderer to use for iOS and Android.
- Bumps iOS to the latest version
- Adds conditional Android namespace: https://github.com/rive-app/rive-react-native/pull/245
```js
export default function Main() {
// Configure the defualt renderer to use for both iOS and Android.
// For more information: https://rive.app/community/doc/overview/docD20dU9Rod
//
// This is optional. The current defaults are:
// - iOS: Skia
// - Android: Skia
// In the future the default will be the Rive Renderer (RiveRendererIOS.Rive and RiveRendererAndroid.Rive)
//
useEffect(() => {
RiveRenderer.defaultRenderer(
RiveRendererIOS.Rive,
RiveRendererAndroid.Skia
);
}, []);
return <App />;
}
```
For more information, see: https://rive.app/community/doc/overview/docD20dU9Rod
Options …

chore: release 7.1.0

---

example/ios/Podfile.lock
package.json
rive-react-native.podspec

Bump iOS to `v5.12.1`, see [iOS Changelog](https://github.com/rive-app/rive-ios/blob/main/CHANGELOG.md)
- Fix libjpg on Mac Sonomaios
- only start/stop the audio engine if it has been initialized

chore: release v7.1.1

---

android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
example/app/(examples)/OutOfBandAssets.tsx
ios/RiveReactNativeView.swift

This PR exposes a way to update referenced assets by modifying the properties that are passed in through the view.
Previously, it would result in the entire `riv` file being reloaded. Now it's possible to update specific referenced assets without reloading the .riv file. Steps in the underlying implementation:
- Conditionally check to see if the assets have changed. This is a combination of name (key) and source (value)
- If there is a change, only update the assets that have a new source
- Uses the same mechanisms that are currently available to load in the asset
Example JS code:
```js
// Initial value
const [uri, setUri] = React.useState('https://picsum.photos/id/372/500/500');
...
<Rive
autoplay={true}
fit={Fit.Contain}
style={styles.animation}
stateMachineName="State Machine 1"
// …
```

feat: add updatable referenced assets

---

ios/RiveReactNativeView.swift

So I had a weird crash found in my app when clicking the rive at a certain point (something like the exit state). The crash seemed to be caused by the `handleTouch` method from `RiveReactNativeView.swift`. 
Specifically at this line:
`inArtboard: viewModel.riveModel!.artboard!.bounds()` where Xcode would throw `Unexpectedly found nil while unwrapping an Optional value`.
The fix proposed by gpt was the one from the PR.
Hope I didn't mess any contributing rules, as this is my first fork + PR contribution, and I hope it helps.

Fix: touching the rive can cause a crash on iOS

---

example/ios/Podfile.lock
package.json

Action failed, manually bumping and tagging after

chore: release 9.5.0
